// Generates public/theme.css (run: node src-web/gen-theme.mjs > public/theme.css)
// — a global override stylesheet that reskins
// App.tsx's dark-fantasy Tailwind palette to the paper/ink palette from
// prototypes/ui-mockup/index.html, WITHOUT touching App.tsx's 36k lines.
//
// Mechanism: Tailwind CDN bakes arbitrary-value classes like `bg-[#0a0f0a]`
// literally into the DOM `class` attribute — CSS attribute selectors match
// that raw string regardless of how Tailwind compiles its own rules, so
// `!important` overrides always win over Tailwind's generated (non-!important)
// rules.
//
// IMPORTANT: selectors use `[class~="token"]` (exact whitespace-delimited
// token match), NOT `[class*="token"]` (substring match). A substring match
// on e.g. `bg-[#cda45e]` also matches inside `hover:bg-[#cda45e]/10` — which
// broke a real button (permanently ink-on-ink, not just on :hover) during
// verification. Exact-token matching requires enumerating every opacity
// suffix (`/10`, `/40`, ...) actually used in the source as its own token,
// since `bg-[#cda45e]` and `bg-[#cda45e]/10` are different complete tokens.

const OPACITY_STEPS = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 98, 99];

// [old hex, target hex/rgb-triplet for opaque use, [r,g,b] for alpha-blended bg use, label]
const COLOR_MAP = [
  ['#0a0f0a', '#F5EFE0', [245, 239, 224], 'nền app tối nhất -> giấy'],
  ['#101a10', '#EDE5D0', [237, 229, 208], 'nền panel -> giấy đậm'],
  ['#1b2a1b', '#EDE5D0', [237, 229, 208], 'nền panel -> giấy đậm'],
  ['#162216', '#F5EFE0', [245, 239, 224], 'nền thẻ/card -> giấy'],
  ['#cda45e', '#1A1512', [26, 21, 18], 'vàng chủ đạo -> mực'],
  ['#e8d3a1', '#1A1512', [26, 21, 18], 'chữ tiêu đề sáng -> mực'],
  ['#8ba888', 'rgba(26,21,18,.6)', [26, 21, 18], 'chữ phụ -> mực nhạt (ink-60)'],
  ['#a3b8a3', 'rgba(26,21,18,.38)', [26, 21, 18], 'chữ phụ nhạt hơn -> mực rất nhạt (ink-38)'],
  ['#8b1515', '#8a3324', [138, 51, 36], 'đỏ cảnh báo -> đỏ mực'],
  ['#a01818', '#8a3324', [138, 51, 36], 'đỏ cảnh báo -> đỏ mực'],
  ['#8b0000', '#8a3324', [138, 51, 36], 'đỏ cảnh báo -> đỏ mực'],
  ['#ff4d4d', '#8a3324', [138, 51, 36], 'đỏ cảnh báo -> đỏ mực'],
  ['#0a0505', '#F5EFE0', [245, 239, 224], 'nền tối (wrapper toàn màn hình) -> giấy'],
  ['#050805', '#F5EFE0', [245, 239, 224], 'nền tối nhất (gradient stop) -> giấy'],
  ['#0d160d', '#EDE5D0', [237, 229, 208], 'nền tối vừa (gradient via-stop) -> giấy đậm'],
  ['#080d08', '#EDE5D0', [237, 229, 208], 'nền hộp trạng thái (status box) -> giấy đậm'],
  ['#4a6b4a', 'rgba(26,21,18,.38)', [26, 21, 18], 'viền track toggle (tắt) -> mực rất nhạt (ink-38)'],
  // 2 màu "feature-toggle accent" trước cố tình bỏ qua — đổi theo yêu cầu
  // user 2026-08-15 (chấp nhận đánh đổi: dùng chung với chỉ báo lượt đánh
  // trong combat, teal/indigo -> mực khiến lượt người chơi bớt nổi bật,
  // nhưng vẫn phân biệt được với đỏ mực của lượt địch).
  ['#5eead4', '#1A1512', [26, 21, 18], 'toggle teal (Miễn trừ nút thắt, bật) -> mực'],
  ['#a5b4fc', '#1A1512', [26, 21, 18], 'toggle indigo (Ký Sinh Tâm Linh, bật) -> mực'],
  // Nút CTA "Phân Tích & Tiếp Tục" (Thiết Lập Đồng Nhân) — theo yêu cầu user
  // 2026-08-15: đổi thành nút "đảo màu" nổi bật (nền mực đen) thay vì xanh rêu
  // sót lại từ theme cũ. #233523 chỉ khớp token trần `bg-[#233523]` (không có
  // tiền tố hover:) DUY NHẤT ở nút này trong toàn bộ App.tsx (verify bằng
  // grep) — 8 chỗ khác đều là `hover:bg-[#233523]`, token khác, generator
  // không match tới nên không bị ảnh hưởng. #324a32 chỉ dùng ở đúng 1 chỗ
  // (hover của nút này). Viền/chữ của nút này (border-[#cda45e]/text-[#e8d3a1])
  // vẫn bị rule chung phía trên đổi thành mực — cần rule ngoại lệ riêng bên
  // dưới đảo ngược lại thành màu giấy, nếu không sẽ bị mực-trên-mực.
  ['#233523', '#1A1512', [26, 21, 18], 'nền nút CTA "Phân Tích & Tiếp Tục" -> mực đen (nút đảo màu)'],
  ['#324a32', '#1A1512', [26, 21, 18], 'hover nền nút CTA "Phân Tích & Tiếp Tục" -> mực đen'],
];

const SIDE_BORDER_PROPS = {
  't': ['border-top-color'], 'b': ['border-bottom-color'],
  'l': ['border-left-color'], 'r': ['border-right-color'],
  'x': ['border-left-color', 'border-right-color'],
  'y': ['border-top-color', 'border-bottom-color'],
};

const alpha2 = (n) => (n === 100 ? '1' : n === 0 ? '0' : `.${n < 10 ? '0' + n : n}`);
const rgba = ([r, g, b], step) => `rgba(${r},${g},${b},${alpha2(step)})`;

let out = `/* AUTO-GENERATED by gen-theme.mjs — do not hand-edit, regenerate instead.
 * Reskins App.tsx (dark-fantasy Tailwind palette) to the paper/ink palette
 * from prototypes/ui-mockup/index.html, approved 2026-08-14 (see
 * production/session-state/active.md). Overrides Tailwind CDN's arbitrary-
 * value utility classes via exact-token attribute selectors (see file-top
 * comment on why [class~=] not [class*=]) + !important — App.tsx's source
 * is untouched. What was deliberately left unchanged: rarity-tier colors,
 * social icons, feature-toggle accent colors, combat VFX (.vfx-* classes).
 */

:root {
  --paper: #F5EFE0;
  --paper-deep: #EDE5D0;
  --ink: #1A1512;
  --ink-60: rgba(26, 21, 18, .60);
  --ink-38: rgba(26, 21, 18, .38);
  --ink-15: rgba(26, 21, 18, .15);
  --danger-ink: #8a3324;
}

/* ---- serif type everywhere, overriding both Tailwind font classes and
   inline style={{fontFamily:...}} (an !important external rule beats a
   plain inline style per the CSS cascade) ---- */
#root, #root * {
  font-family: "Palatino Linotype", "Noto Serif", "Times New Roman", serif !important;
}

/* ---- drop the 3 dark-fantasy background photos, flat paper instead ---- */
[style*="kimlove136-gif/anh-nen-game"] {
  background-image: none !important;
  background-color: var(--paper) !important;
}

/* ---- neutralize the gold/teal/indigo glow shadows AND the generic
   dark-elevation shadows (paper/ink has no glow, and flat "no shadow" is
   the established look for cards/panels here — see .glowing-card and the
   vignette-neutralize block below). Added 2026-08-15: rgba(0,0,0,..) and
   rgba(10,20,10,..) (~48 combined occurrences) are used throughout the
   dark-fantasy source purely for depth/elevation against a DARK
   background — invisible/blended there, but on the new light paper
   background they render as a visible dark halo (confirmed: a dialogue
   bubble's shadow-[0_4px_15px_rgba(0,0,0,0.3)], reported as "text has a
   shadow" — it's a box-shadow on the bubble, not an actual text-shadow,
   but reads the same way visually).
   Left as a substring match deliberately: it's inside a much longer
   shadow-[...] arbitrary value (not a standalone token), and "no shadow"
   is correct whether or not a hover: prefix is present, so the earlier
   hover-false-positive bug doesn't apply here. ---- */
[class*="rgba(205,164,94"], [class*="rgba(94,234,212"], [class*="rgba(165,180,252"],
[class*="rgba(0,0,0,"], [class*="rgba(10,20,10,"] {
  box-shadow: none !important;
}

/* ---- .glowing-card: hand-written CSS class (App.tsx has its own <style>
   block, not a Tailwind utility) for the adventure-mode selection cards —
   same dark-gradient-card role as the bg-[#162216] family above, just not
   expressible as a class-attribute selector. Found via verification pass
   on the character-creation screen. ---- */
.glowing-card {
  background: var(--paper) !important;
  box-shadow: none !important;
}

/* ---- neutralize decorative radial/linear-gradient vignette backgrounds.
   Tailwind arbitrary values like bg-[radial-gradient(circle_at_center,rgba(
   ...)_0%,rgba(...)_100%)] embed a whole gradient function in one class —
   the hex/rgba selectors below can't match this syntax, and there's no
   hover: variant of these in the source (checked), so a substring match is
   safe here. Found via verification: a full-viewport z-[-2] vignette was
   the actual source of a leftover dark background outside the reskinned
   panel. Paper/ink has no glow/vignette — goes fully transparent (not
   opaque paper; some sit as overlays ON TOP of content). ---- */
[class*="bg-[radial-gradient("], [class*="bg-[linear-gradient("] {
  background-image: none !important;
  background-color: transparent !important;
}

/* ---- nút CTA "Phân Tích & Tiếp Tục" (Thiết Lập Đồng Nhân): nền của nó
   (token bg-[#233523], xem COLOR_MAP) đổi thành mực đen để làm nút "đảo
   màu" nổi bật — nhưng viền/chữ (border-[#cda45e], text-[#e8d3a1]) vẫn bị
   rule chung ở dưới đổi thành mực do dùng chung token với hàng trăm chỗ
   khác trên nền giấy. Combined-attribute-selector (đặc thù cao hơn 1
   attribute selector đơn) để chỉ đảo ngược viền/chữ riêng nút này, không
   đụng tới #cda45e/#e8d3a1 ở nơi khác. ---- */
[class~="bg-[#233523]"][class~="border-[#cda45e]"] { border-color: var(--paper) !important; }
[class~="bg-[#233523]"][class~="text-[#e8d3a1]"] { color: var(--paper) !important; }

`;

// ---- standard Tailwind named-palette utilities (bg-black, text-white,
// bg-gray-800, ...) — not bracket-arbitrary-value classes, so not caught
// above. `black`/`white` get the paper/ink swap; opacity-suffixed variants
// (bg-black/60, a translucent scrim OR a solid-ish component field
// depending on where it's used — see comment below) get a proportional
// paper-deep tint at the SAME alpha rather than going flat opaque or flat
// transparent, since either flat choice broke one of the two use cases
// during verification.
const NAMED_MAP = [
  ['black', 'var(--paper)', 'var(--ink)', 'đen (scrim/nền tối) -> giấy / mực'],
  ['white', 'var(--paper)', 'var(--ink)', 'trắng (chữ/viền trên nền tối) -> giấy / mực'],
  ['gray-900', 'var(--paper-deep)', 'var(--ink)', 'xám rất đậm -> giấy đậm / mực'],
  ['gray-800', 'var(--paper-deep)', 'var(--ink)', 'xám đậm -> giấy đậm / mực'],
  ['gray-700', 'var(--paper-deep)', 'var(--ink)', 'xám đậm vừa -> giấy đậm / mực'],
  ['gray-600', 'var(--paper-deep)', 'var(--ink-60)', 'xám vừa -> giấy đậm / mực nhạt'],
  ['gray-500', 'var(--paper-deep)', 'var(--ink-60)', 'xám nhạt -> giấy đậm / mực nhạt'],
];

// ---- hover: variants (added 2026-08-15, following a confirmed bug: a
// button's base bg-[#1b2a1b] gets reskinned to paper-deep, but its SEPARATE
// hover:bg-[#1b2a1b] token was never targeted at all — Tailwind CDN's own
// (non-!important) hover rule then shows through the ORIGINAL unskinned dark
// color on actual mouse-hover, while text-[#e8d3a1]'s unconditional
// (non-hover-gated) !important ink rule stays black regardless of hover
// state — black text on unskinned dark green = unreadable. This was a
// systemic gap, not one button: `hover:` is a COMPLETE separate class token
// from the bare one (`hover:bg-[#1b2a1b]` vs `bg-[#1b2a1b]`), and every rule
// above/below only ever targets the bare token.
// Fix: emit a mirrored rule for the literal `hover:${tok}` token, gated by
// an ACTUAL `:hover` pseudo-class in the selector — this is safe (only
// overrides while truly hovering) and is NOT the substring-match bug the
// file-top comment warns about (that was `[class*=]` matching `hover:bg-X`
// as a SUBSTRING of `bg-X` and applying permanently; this is `[class~=]`
// exact-matching the distinct `hover:bg-X` token, active only on `:hover`).
function hoverSel(tok) { return `[class~="hover:${tok}"]:hover`; }

for (const [name, bgVal, fgVal, label] of NAMED_MAP) {
  out += `/* Tailwind ${name} -> bg:${bgVal} text/border:${fgVal}  (${label}) */\n`;
  out += `[class~="bg-${name}"] { background-color: ${bgVal} !important; }\n`;
  out += `[class~="text-${name}"] { color: ${fgVal} !important; }\n`;
  out += `[class~="border-${name}"] { border-color: ${fgVal} !important; }\n`;
  out += `[class~="placeholder-${name}"]::placeholder { color: ${fgVal} !important; }\n`;
  out += `[class~="ring-${name}"] { --tw-ring-color: ${fgVal} !important; }\n`;
  out += `${hoverSel(`bg-${name}`)} { background-color: ${bgVal} !important; }\n`;
  out += `${hoverSel(`text-${name}`)} { color: ${fgVal} !important; }\n`;
  out += `${hoverSel(`border-${name}`)} { border-color: ${fgVal} !important; }\n`;
}
out += `\n/* bg-black/NN, bg-white/NN -> paper-deep tint at the same alpha (scrim AND component-field use cases both need this — see NAMED_MAP comment) */\n`;
for (const step of OPACITY_STEPS) {
  out += `[class~="bg-black/${step}"], [class~="bg-white/${step}"] { background-color: ${rgba([237, 229, 208], step)} !important; }\n`;
  out += `${hoverSel(`bg-black/${step}`)}, ${hoverSel(`bg-white/${step}`)} { background-color: ${rgba([237, 229, 208], step)} !important; }\n`;
}
out += `\n`;

// ---- the 16 mapped hex-bracket colors, base token + every opacity step.
// bg- gets a proportional alpha blend (same reasoning as bg-black/white
// above — some of these are full-cover overlays, going flat opaque would
// hide content beneath, as happened during verification). text-/border-/
// etc. go flat opaque at every opacity step — losing the subtlety of e.g.
// "40% vs 60% opacity border" is a minor cosmetic gap, not a correctness
// bug, unlike backgrounds.
function emitTokenRules(tok, bgv, flatVal) {
  let s = '';
  s += `[class~="bg-${tok}"] { background-color: ${bgv} !important; }\n`;
  s += `[class~="text-${tok}"] { color: ${flatVal} !important; }\n`;
  s += `[class~="border-${tok}"] { border-color: ${flatVal} !important; }\n`;
  for (const [side, props] of Object.entries(SIDE_BORDER_PROPS)) {
    s += `[class~="border-${side}-${tok}"] { ${props.map(p => `${p}: ${flatVal} !important;`).join(' ')} }\n`;
  }
  s += `[class~="ring-${tok}"] { --tw-ring-color: ${flatVal} !important; }\n`;
  s += `[class~="from-${tok}"] { --tw-gradient-from: ${flatVal} !important; }\n`;
  // via- is special: Tailwind CDN's arbitrary-value JIT does NOT reference
  // --tw-gradient-via when building the final --tw-gradient-stops list for
  // a bracket via-[#hex]/NN token — it bakes the ORIGINAL resolved color in
  // as a literal directly inside --tw-gradient-stops, bypassing the
  // variable entirely. Confirmed via live computed-style inspection
  // (2026-08-15): overriding --tw-gradient-via alone left the actual
  // rendered gradient's middle stop showing the unskinned dark color even
  // though --tw-gradient-via itself correctly read as the overridden paper
  // tone — from-/to- don't have this problem (their var() references DO
  // get used in --tw-gradient-stops). Fix: override --tw-gradient-stops
  // directly, chaining through --tw-gradient-from/--tw-gradient-to (which
  // ARE correctly override-able) so it still composes with whatever those
  // resolve to.
  s += `[class~="via-${tok}"] { --tw-gradient-via: ${flatVal} !important; --tw-gradient-stops: var(--tw-gradient-from, transparent), ${flatVal}, var(--tw-gradient-to, transparent) !important; }\n`;
  s += `[class~="to-${tok}"] { --tw-gradient-to: ${flatVal} !important; }\n`;
  s += `[class~="decoration-${tok}"] { text-decoration-color: ${flatVal} !important; }\n`;
  s += `[class~="accent-${tok}"] { accent-color: ${flatVal} !important; }\n`;
  s += `[class~="placeholder-${tok}"]::placeholder { color: ${flatVal} !important; }\n`;
  // hover: mirror — same properties/values, gated by a real :hover so it
  // only overrides while actually hovering (see hoverSel() comment above).
  s += `${hoverSel(`bg-${tok}`)} { background-color: ${bgv} !important; }\n`;
  s += `${hoverSel(`text-${tok}`)} { color: ${flatVal} !important; }\n`;
  s += `${hoverSel(`border-${tok}`)} { border-color: ${flatVal} !important; }\n`;
  for (const [side, props] of Object.entries(SIDE_BORDER_PROPS)) {
    s += `${hoverSel(`border-${side}-${tok}`)} { ${props.map(p => `${p}: ${flatVal} !important;`).join(' ')} }\n`;
  }
  s += `${hoverSel(`ring-${tok}`)} { --tw-ring-color: ${flatVal} !important; }\n`;
  s += `${hoverSel(`from-${tok}`)} { --tw-gradient-from: ${flatVal} !important; }\n`;
  s += `${hoverSel(`via-${tok}`)} { --tw-gradient-via: ${flatVal} !important; --tw-gradient-stops: var(--tw-gradient-from, transparent), ${flatVal}, var(--tw-gradient-to, transparent) !important; }\n`;
  s += `${hoverSel(`to-${tok}`)} { --tw-gradient-to: ${flatVal} !important; }\n`;
  s += `${hoverSel(`decoration-${tok}`)} { text-decoration-color: ${flatVal} !important; }\n`;
  s += `${hoverSel(`accent-${tok}`)} { accent-color: ${flatVal} !important; }\n`;
  return s;
}

for (const [oldHex, flatVal, rgbTriplet, label] of COLOR_MAP) {
  const base = `[#${oldHex.slice(1)}]`;
  out += `/* ${oldHex} -> ${flatVal}  (${label}) */\n`;
  // bare 100%-opacity token (no numeric suffix). For bg-, always use a
  // SOLID color even when flatVal is itself an rgba(...) form (the
  // ink-60/ink-38 muted-text entries) — a translucent ink-60 used as a flat
  // background blends with whatever's underneath into a washed-out gray
  // (found on a toggle-switch knob: bg-[#8ba888], no opacity suffix, meant
  // to read as a solid ink dot, not a faded smudge). text-/border- keep the
  // muted rgba form, which IS the intended look there.
  const bgFlatVal = flatVal.startsWith('rgba') ? '#1A1512' : flatVal;
  out += emitTokenRules(base, bgFlatVal, flatVal);
  // every opacity-suffixed token actually reachable in Tailwind's syntax
  for (const step of OPACITY_STEPS) {
    out += emitTokenRules(`${base}/${step}`, rgba(rgbTriplet, step), flatVal);
  }
  out += `\n`;
}

// ---- correction: hover:bg-[#233523] must NOT inherit #233523's own bare-
// token mapping (ink/mực đen). #233523 has exactly 2 distinct roles in the
// source (verified 2026-08-15 via grep): (1) the BARE token `bg-[#233523]`
// — used ONLY once, as the base background of the "Phân Tích & Tiếp Tục"
// combat CTA button, intentionally an inverted ink button (see the
// combined-selector exception above that flips ITS border/text to paper);
// (2) `hover:bg-[#233523]` — used ~8 OTHER places as the generic
// hover-highlight of buttons whose base is `bg-[#1b2a1b]` (paper-deep) or
// `bg-transparent`, i.e. it plays the exact same role as #1b2a1b's own
// hover state everywhere else, NOT the CTA's role. Those buttons' text
// stays ink (never flipped to paper), so if the automatic hover-mirror
// above (which — correctly for role (1) — copies the bare token's ink
// mapping onto the hover: token too) is left as the final word, all 8
// generic buttons get an ink hover background under ink text on hover =
// unreadable, same defect class as the original hover: gap this whole
// hover-mirroring feature exists to fix. Since this block runs AFTER the
// COLOR_MAP loop, same-specificity + !important ties resolve by source
// order — this wins and correctly overrides ONLY the hover: token role
// back to the paper-deep family (matching #1b2a1b's own hover treatment).
out += `/* hover:bg-[#233523] correction — see comment above: hover role only, paper-deep family (like #1b2a1b), NOT the bare token's ink/CTA role */\n`;
out += `[class~="hover:bg-[#233523]"]:hover { background-color: #EDE5D0 !important; }\n`;
for (const step of OPACITY_STEPS) {
  out += `[class~="hover:bg-[#233523]/${step}"]:hover { background-color: ${rgba([237, 229, 208], step)} !important; }\n`;
}

console.log(out);
