// Generates public/theme.css (run: node src-web/gen-theme.mjs > public/theme.css)
// — a global override stylesheet that reskins
// App.tsx's dark-fantasy Tailwind palette to the paper/ink palette from
// prototypes/ui-mockup/index.html, WITHOUT touching App.tsx's 36k lines.
//
// Mechanism: Tailwind CDN bakes arbitrary-value classes like `bg-[#0a0f0a]`
// literally into the DOM `class` attribute — CSS attribute selectors match
// that raw string regardless of how Tailwind compiles its own rules, so
// `!important` overrides always win over Tailwind's generated (non-!important)
// rules.
//
// IMPORTANT: selectors use `[class~="token"]` (exact whitespace-delimited
// token match), NOT `[class*="token"]` (substring match). A substring match
// on e.g. `bg-[#cda45e]` also matches inside `hover:bg-[#cda45e]/10` — which
// broke a real button (permanently ink-on-ink, not just on :hover) during
// verification. Exact-token matching requires enumerating every opacity
// suffix (`/10`, `/40`, ...) actually used in the source as its own token,
// since `bg-[#cda45e]` and `bg-[#cda45e]/10` are different complete tokens.

const OPACITY_STEPS = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95];

// [old hex, target hex/rgb-triplet for opaque use, [r,g,b] for alpha-blended bg use, label]
const COLOR_MAP = [
  ['#0a0f0a', '#F5EFE0', [245, 239, 224], 'nền app tối nhất -> giấy'],
  ['#101a10', '#EDE5D0', [237, 229, 208], 'nền panel -> giấy đậm'],
  ['#1b2a1b', '#EDE5D0', [237, 229, 208], 'nền panel -> giấy đậm'],
  ['#162216', '#F5EFE0', [245, 239, 224], 'nền thẻ/card -> giấy'],
  ['#cda45e', '#1A1512', [26, 21, 18], 'vàng chủ đạo -> mực'],
  ['#e8d3a1', '#1A1512', [26, 21, 18], 'chữ tiêu đề sáng -> mực'],
  ['#8ba888', 'rgba(26,21,18,.6)', [26, 21, 18], 'chữ phụ -> mực nhạt (ink-60)'],
  ['#a3b8a3', 'rgba(26,21,18,.38)', [26, 21, 18], 'chữ phụ nhạt hơn -> mực rất nhạt (ink-38)'],
  ['#8b1515', '#8a3324', [138, 51, 36], 'đỏ cảnh báo -> đỏ mực'],
  ['#a01818', '#8a3324', [138, 51, 36], 'đỏ cảnh báo -> đỏ mực'],
  ['#8b0000', '#8a3324', [138, 51, 36], 'đỏ cảnh báo -> đỏ mực'],
  ['#ff4d4d', '#8a3324', [138, 51, 36], 'đỏ cảnh báo -> đỏ mực'],
  ['#0a0505', '#F5EFE0', [245, 239, 224], 'nền tối (wrapper toàn màn hình) -> giấy'],
  ['#050805', '#F5EFE0', [245, 239, 224], 'nền tối nhất (gradient stop) -> giấy'],
  ['#0d160d', '#EDE5D0', [237, 229, 208], 'nền tối vừa (gradient via-stop) -> giấy đậm'],
  ['#080d08', '#EDE5D0', [237, 229, 208], 'nền hộp trạng thái (status box) -> giấy đậm'],
  ['#4a6b4a', 'rgba(26,21,18,.38)', [26, 21, 18], 'viền track toggle (tắt) -> mực rất nhạt (ink-38)'],
];

const SIDE_BORDER_PROPS = {
  't': ['border-top-color'], 'b': ['border-bottom-color'],
  'l': ['border-left-color'], 'r': ['border-right-color'],
  'x': ['border-left-color', 'border-right-color'],
  'y': ['border-top-color', 'border-bottom-color'],
};

const alpha2 = (n) => (n === 100 ? '1' : n === 0 ? '0' : `.${n < 10 ? '0' + n : n}`);
const rgba = ([r, g, b], step) => `rgba(${r},${g},${b},${alpha2(step)})`;

let out = `/* AUTO-GENERATED by gen-theme.mjs — do not hand-edit, regenerate instead.
 * Reskins App.tsx (dark-fantasy Tailwind palette) to the paper/ink palette
 * from prototypes/ui-mockup/index.html, approved 2026-08-14 (see
 * production/session-state/active.md). Overrides Tailwind CDN's arbitrary-
 * value utility classes via exact-token attribute selectors (see file-top
 * comment on why [class~=] not [class*=]) + !important — App.tsx's source
 * is untouched. What was deliberately left unchanged: rarity-tier colors,
 * social icons, feature-toggle accent colors, combat VFX (.vfx-* classes).
 */

:root {
  --paper: #F5EFE0;
  --paper-deep: #EDE5D0;
  --ink: #1A1512;
  --ink-60: rgba(26, 21, 18, .60);
  --ink-38: rgba(26, 21, 18, .38);
  --ink-15: rgba(26, 21, 18, .15);
  --danger-ink: #8a3324;
}

/* ---- serif type everywhere, overriding both Tailwind font classes and
   inline style={{fontFamily:...}} (an !important external rule beats a
   plain inline style per the CSS cascade) ---- */
#root, #root * {
  font-family: "Palatino Linotype", "Noto Serif", "Times New Roman", serif !important;
}

/* ---- drop the 3 dark-fantasy background photos, flat paper instead ---- */
[style*="kimlove136-gif/anh-nen-game"] {
  background-image: none !important;
  background-color: var(--paper) !important;
}

/* ---- neutralize the gold glow/shadow effect (paper/ink has no glow).
   Left as a substring match deliberately: it's inside a much longer
   shadow-[...] arbitrary value (not a standalone token), and "no shadow"
   is correct whether or not a hover: prefix is present, so the earlier
   hover-false-positive bug doesn't apply here. ---- */
[class*="rgba(205,164,94"] {
  box-shadow: none !important;
}

/* ---- .glowing-card: hand-written CSS class (App.tsx has its own <style>
   block, not a Tailwind utility) for the adventure-mode selection cards —
   same dark-gradient-card role as the bg-[#162216] family above, just not
   expressible as a class-attribute selector. Found via verification pass
   on the character-creation screen. ---- */
.glowing-card {
  background: var(--paper) !important;
  box-shadow: none !important;
}

/* ---- neutralize decorative radial/linear-gradient vignette backgrounds.
   Tailwind arbitrary values like bg-[radial-gradient(circle_at_center,rgba(
   ...)_0%,rgba(...)_100%)] embed a whole gradient function in one class —
   the hex/rgba selectors below can't match this syntax, and there's no
   hover: variant of these in the source (checked), so a substring match is
   safe here. Found via verification: a full-viewport z-[-2] vignette was
   the actual source of a leftover dark background outside the reskinned
   panel. Paper/ink has no glow/vignette — goes fully transparent (not
   opaque paper; some sit as overlays ON TOP of content). ---- */
[class*="bg-[radial-gradient("], [class*="bg-[linear-gradient("] {
  background-image: none !important;
  background-color: transparent !important;
}

`;

// ---- standard Tailwind named-palette utilities (bg-black, text-white,
// bg-gray-800, ...) — not bracket-arbitrary-value classes, so not caught
// above. `black`/`white` get the paper/ink swap; opacity-suffixed variants
// (bg-black/60, a translucent scrim OR a solid-ish component field
// depending on where it's used — see comment below) get a proportional
// paper-deep tint at the SAME alpha rather than going flat opaque or flat
// transparent, since either flat choice broke one of the two use cases
// during verification.
const NAMED_MAP = [
  ['black', 'var(--paper)', 'var(--ink)', 'đen (scrim/nền tối) -> giấy / mực'],
  ['white', 'var(--paper)', 'var(--ink)', 'trắng (chữ/viền trên nền tối) -> giấy / mực'],
  ['gray-900', 'var(--paper-deep)', 'var(--ink)', 'xám rất đậm -> giấy đậm / mực'],
  ['gray-800', 'var(--paper-deep)', 'var(--ink)', 'xám đậm -> giấy đậm / mực'],
  ['gray-700', 'var(--paper-deep)', 'var(--ink)', 'xám đậm vừa -> giấy đậm / mực'],
  ['gray-600', 'var(--paper-deep)', 'var(--ink-60)', 'xám vừa -> giấy đậm / mực nhạt'],
  ['gray-500', 'var(--paper-deep)', 'var(--ink-60)', 'xám nhạt -> giấy đậm / mực nhạt'],
];

for (const [name, bgVal, fgVal, label] of NAMED_MAP) {
  out += `/* Tailwind ${name} -> bg:${bgVal} text/border:${fgVal}  (${label}) */\n`;
  out += `[class~="bg-${name}"] { background-color: ${bgVal} !important; }\n`;
  out += `[class~="text-${name}"] { color: ${fgVal} !important; }\n`;
  out += `[class~="border-${name}"] { border-color: ${fgVal} !important; }\n`;
  out += `[class~="placeholder-${name}"]::placeholder { color: ${fgVal} !important; }\n`;
  out += `[class~="ring-${name}"] { --tw-ring-color: ${fgVal} !important; }\n`;
}
out += `\n/* bg-black/NN, bg-white/NN -> paper-deep tint at the same alpha (scrim AND component-field use cases both need this — see NAMED_MAP comment) */\n`;
for (const step of OPACITY_STEPS) {
  out += `[class~="bg-black/${step}"], [class~="bg-white/${step}"] { background-color: ${rgba([237, 229, 208], step)} !important; }\n`;
}
out += `\n`;

// ---- the 16 mapped hex-bracket colors, base token + every opacity step.
// bg- gets a proportional alpha blend (same reasoning as bg-black/white
// above — some of these are full-cover overlays, going flat opaque would
// hide content beneath, as happened during verification). text-/border-/
// etc. go flat opaque at every opacity step — losing the subtlety of e.g.
// "40% vs 60% opacity border" is a minor cosmetic gap, not a correctness
// bug, unlike backgrounds.
function emitTokenRules(tok, bgv, flatVal) {
  let s = '';
  s += `[class~="bg-${tok}"] { background-color: ${bgv} !important; }\n`;
  s += `[class~="text-${tok}"] { color: ${flatVal} !important; }\n`;
  s += `[class~="border-${tok}"] { border-color: ${flatVal} !important; }\n`;
  for (const [side, props] of Object.entries(SIDE_BORDER_PROPS)) {
    s += `[class~="border-${side}-${tok}"] { ${props.map(p => `${p}: ${flatVal} !important;`).join(' ')} }\n`;
  }
  s += `[class~="ring-${tok}"] { --tw-ring-color: ${flatVal} !important; }\n`;
  s += `[class~="from-${tok}"] { --tw-gradient-from: ${flatVal} !important; }\n`;
  s += `[class~="via-${tok}"] { --tw-gradient-via: ${flatVal} !important; }\n`;
  s += `[class~="to-${tok}"] { --tw-gradient-to: ${flatVal} !important; }\n`;
  s += `[class~="decoration-${tok}"] { text-decoration-color: ${flatVal} !important; }\n`;
  s += `[class~="accent-${tok}"] { accent-color: ${flatVal} !important; }\n`;
  s += `[class~="placeholder-${tok}"]::placeholder { color: ${flatVal} !important; }\n`;
  return s;
}

for (const [oldHex, flatVal, rgbTriplet, label] of COLOR_MAP) {
  const base = `[#${oldHex.slice(1)}]`;
  out += `/* ${oldHex} -> ${flatVal}  (${label}) */\n`;
  // bare 100%-opacity token (no numeric suffix). For bg-, always use a
  // SOLID color even when flatVal is itself an rgba(...) form (the
  // ink-60/ink-38 muted-text entries) — a translucent ink-60 used as a flat
  // background blends with whatever's underneath into a washed-out gray
  // (found on a toggle-switch knob: bg-[#8ba888], no opacity suffix, meant
  // to read as a solid ink dot, not a faded smudge). text-/border- keep the
  // muted rgba form, which IS the intended look there.
  const bgFlatVal = flatVal.startsWith('rgba') ? '#1A1512' : flatVal;
  out += emitTokenRules(base, bgFlatVal, flatVal);
  // every opacity-suffixed token actually reachable in Tailwind's syntax
  for (const step of OPACITY_STEPS) {
    out += emitTokenRules(`${base}/${step}`, rgba(rgbTriplet, step), flatVal);
  }
  out += `\n`;
}

console.log(out);
